SistemaArtigo/SistemaArtigo/Models/CartaoCredito.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SistemaArtigo.Models
{
    public class CartaoCredito
    {
        public int Numero { get; set; }
        public DateTime Validade { get; set; }
        public string Bandeira { get; set; }
    }
}

SistemaArtigo/SistemaArtigo/Models/Endereco.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SistemaArtigo.Models
{
    public class Endereco
    {
        public string Rua { get; set; }
        public string Cep { get; set; }
        public int Numero { get; set; }
        public string Complemento { get; set; }
        public string Bairro { get; set; }
        public string Cidade { get; set; }
        public string Estado { get; set; }
    }
}

SistemaArtigo/SistemaArtigo/Models/Pessoa.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace SistemaArtigo.Models
{
    public class Pessoa
    {
        [Required]
        public string Nome { get; set; }

        [Required]
        public int Telefone { get; set; }

        [Required]
        public string Email { get; set; }

        [Required]
        [Display(Name ="Local De Participação")]
        public string LocalParticipacao { get; set; }

        [Required]
        
        public Endereco Endereco { get; set; }

        [Required]
        public CartaoCredito CartaoCredito { get; set; }

       [Required]
        public string Senha { get; set; }
        [Required]
        [Display(Name = "Repita a sua senha:")]
        public string RepitaSenha { get; set; }
    }
}

SistemaArtigo/SistemaArtigo/Controllers/EnvioArtigoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SistemaArtigo.Controllers
{
    public class EnvioArtigoController : Controller
    {
        // GET: EnvioArtigo
        public ActionResult EnviarArtigo()
        {
            return View();
        }
    }
}

SistemaArtigo/SistemaArtigo/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SistemaArtigo.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

SistemaArtigo/SistemaArtigo/Controllers/InscricaoController.cs
using SistemaArtigo.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SistemaArtigo.Controllers
{
    public class InscricaoController : Controller
    {
        // GET: Inscricao
        public ActionResult Login()
        {
            return View();
        }

        // POST: Inscricao/Index
        [HttpPost]
        public ActionResult Login(Pessoa pessoa)
        {
            try
            {
                var teste = pessoa;

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Inscricao()
        {
            return View();
        }


    }
}

SistemaArtigo/SistemaArtigo/Views/EnvioArtigo/EnviarArtigo.cshtml
@{
    ViewBag.Title = "EnviarArtigo";
}

<h2>EnviarArtigo</h2><br />
<hr/>
<form action="/EnvioArtigo/EnvioArtigo" method="post">
    Nome dos Participantes
    <input type="text" name="Nome" /><br />

    Numero de Inscrição dos Autores
    <input type="text" /><br />

    Email dos Autores
    <input type="text" /><br />

    Resumo do Artigo <br />

    <textarea name="message" rows="10" cols="80">
    Digite aqui o resumo do artigo
    </textarea>
    <br />

    <input type="file" /> <br />


    <input type="submit" value="Enviar"/>

</form>

SistemaArtigo/SistemaArtigo/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

SistemaArtigo/SistemaArtigo/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

SistemaArtigo/SistemaArtigo/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<h4> Enviar Artigo</h4>

<button>@Html.ActionLink("Enviar Artigo", "EnviarArtigo", "EnvioArtigo")</button> 

<h4> Avaliar Artigo</h4>

SistemaArtigo/SistemaArtigo/Views/Inscricao/Inscricao.cshtml
@model SistemaArtigo.Models.Pessoa

@{
    ViewBag.Title = "Inscrição do Participante";
}

<h2>Inscrição do Participante</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Dados Pessoais</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Telefone, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Telefone, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Telefone, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.LocalParticipacao, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.LocalParticipacao, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.LocalParticipacao, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Senha, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.PasswordFor(model => model.Senha, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Senha, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.RepitaSenha, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.PasswordFor(model => model.RepitaSenha, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.RepitaSenha, "", new { @class = "text-danger" })
        </div>
    </div>

    <hr />
    <h4>Endereço</h4>

    <div class="form-group">
        @Html.LabelFor(model => model.Endereco.Cep, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Endereco.Cep, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Endereco.Cep, "", new { @class = "text-danger" })
        </div>
    </div>



    <div class="form-group">
        @Html.LabelFor(model => model.Endereco.Rua, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Endereco.Rua, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Endereco.Rua, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Endereco.Numero, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Endereco.Numero, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Endereco.Numero, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Endereco.Bairro, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Endereco.Bairro, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Endereco.Bairro, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        @Html.LabelFor(model => model.Endereco.Cidade, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Endereco.Cidade, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Endereco.Cidade, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Endereco.Estado, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Endereco.Estado, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Endereco.Estado, "", new { @class = "text-danger" })
        </div>
    </div>



    <hr />
    <h4>Cartão de Credito</h4>
    <div class="form-group">
        @Html.LabelFor(model => model.CartaoCredito.Numero, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.CartaoCredito.Numero, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.CartaoCredito.Numero, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.CartaoCredito.Bandeira, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.CartaoCredito.Bandeira, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.CartaoCredito.Bandeira, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.CartaoCredito.Validade, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.CartaoCredito.Validade, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.CartaoCredito.Validade, "", new { @class = "text-danger" })
        </div>
    </div>







    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

SistemaArtigo/SistemaArtigo/Views/Inscricao/Login.cshtml
@{
    ViewBag.Title = "Login";
}

<h2>Congresso de Artigos</h2>

<div class="FormLogin">
    <form action="/Inscricao/Login" method="post">
        Login: <input type="text" /> <br />
        Senha: <input type="password" name="Senha" /><br />
        <input type="submit" value="Entrar" />
        <button>@Html.ActionLink("Cadastre-se", "Inscricao", "Inscricao")</button> 
    </form>

</div>

SistemaArtigo/SistemaArtigo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Meu Aplicativo ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Nome do aplicativo", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Início", "Index", "Home")</li>
                    <li>@Html.ActionLink("Sobre", "About", "Home")</li>
                    <li>@Html.ActionLink("Contato", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Meu Aplicativo ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>